apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acmeair-web
  template:
    metadata:
      labels:
        app: acmeair-web
    spec:
      containers:
        - name: acmeair-web
          image: mohibqureshi7/acmeair:acmeair
          ports:
            - containerPort: 9443
          env:
            - name: MONGO_HOST
              value: "mongo-service"  # Use the Service name for MongoDB
            - name: MONGO_PORT
              value: "27017"  # MongoDB default port
          # Other configurations...
